version: "3.8"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./data/es01/:/usr/share/elasticsearch/data/
    networks:
      - elk
    ports:
      - ${ES_PORT}:9200
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  ent-search:
    image: docker.elastic.co/enterprise-search/enterprise-search:${STACK_VERSION}
    depends_on:
      - es01
    ports:
      - 3002:3002
    networks:
      - elk
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - secret_management.encryption_keys=[a09e3592b5ee6366bd8b4f1aff285635094eb4d086038cdc01270bf6cb937ba1]
      - elasticsearch.host=http://es01:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=changeme
      - allow_es_settings_modification=true

  logstash:
    depends_on:
      - es01
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
    networks:
      - elk
    ports:
      - ${LOGSTASH_PORT}:9600
      - 5000:5000
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.monitoring.elasticsearch.hosts=http://es01:9200
      - xpack.monitoring.elasticsearch.username=elastic
      - xpack.monitoring.elasticsearch.password=changeme

  kibana:
    depends_on:
      - es01
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./data/kibana/:/usr/share/kibana/data/
    networks:
      - elk
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ENTERPRISESEARCH_HOST=http://ent-search:3002
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}

networks:
  elk:
    driver: bridge
